import type { Doctor } from "@/types/doctor";

export const DOCTORS: Doctor[] = [
  {
    id: "shakeel_ahmad",
    name: "Mr. Shakeel Ahmad",
    qualification: "",
    specialization: "CEO Hayat Eye Care",
    department: "Management",
    experienceYears: 20,
    languages: ["Hindi", "English", "Urdu"],
    timing: "Mon–Sat",
    rating: 5.0,
    bio: "Started Hayats in 2004.",
    image: "/doctors/shakeel_ahmad.png",
  },
  {
    id: "abdul_mannan",
    name: "Abdul Mannan",
    qualification: "D.R. opt(optometrist) UPSMFAC",
    specialization: "Optical Dispensing",
    department: "Optical Dispensing",
    experienceYears: 12,
    languages: ["Hindi", "English"],
    timing: "Mon–Sat",
    rating: 4.9,
    bio: "Education: D.R. opt(optometrist) UPSMFAC",
    image: "/doctors/abdul_mannan.png",
  },
  {
    id: "jishan_ahmad",
    name: "Jishan Ahmad",
    qualification: "D.R. OPT (Optometrist),UPSMFAC , B.OPT , M.OPT , C.C.L.P",
    specialization: "Chief Optometrist",
    department: "Vision Testing",
    experienceYears: 10,
    languages: ["Hindi", "English", "Urdu"],
    timing: "Mon–Sat",
    rating: 4.9,
    bio: "Education: D.R. OPT (Optometrist), UPSMFAC, B.OPT, M.OPT, C.C.L.P",
    image: "/doctors/jishan_ahmad.png",
  },
  {
    id: "tabinda_akhtar",
    name: "Tabinda Akhtar",
    qualification: "UPSMFAC, D.R. OPT(optometrist)",
    specialization: "Paediatric and Child Specialist",
    department: "Paediatric Care",
    experienceYears: 6,
    languages: ["Hindi", "English"],
    timing: "Mon–Sat",
    rating: 4.9,
    bio: "Education: UPSMFAC, D.R. OPT(optometrist)",
    image: "/doctors/tabinda_akhtar.png",
  },
  {
    id: "owais_hayat",
    name: "Owais Hayat",
    qualification: "D.R. OPT (optometridt ) , UPSMFAC",
    specialization: "Frame Fitting & Refraction Specialist",
    department: "Frame Fitting",
    experienceYears: 5,
    languages: ["Hindi", "English", "Urdu"],
    timing: "Mon–Sun",
    rating: 4.5,
    bio: "Education: D.R. OPT (optometrist), UPSMFAC",
    image: "/doctors/owais_hayat.png",
  },
];
